### ISSUE TITLE
Can u disbale land worldguard region command

### ISSUE THREAD

**Issue by silliershark** [MihaiChirculete/WorldGuard#225] opened 2021-08-28 16:55 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [https://poggit.pmmp.io/p/EconomyLand/2.1.2]

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Can u disable this on region area

**Describe alternatives you've considered**

**Additional context**

**Comment by awgybop1** [comment] 2022-04-27 02:30
Hello,

I am not exactly sure what the issue is or what you need disabled. Looking at the plugin, it does not support API 4 and therefore is no longer compatible with a server running the latest version of WorldGuard anyway, and since this issue is old, I am going to close it. If I can help with anything else, please re-open an issue. Thanks :)

**Closed by awgybop1** 2022-04-27 02:30 UTC
