### ISSUE TITLE
EnderPearl Cooldown doesnt work

### ISSUE THREAD

**Issue by ItsMax123** [MihaiChirculete/WorldGuard#192] opened 2020-10-17 23:03 UTC
**Describe the bug**
When the allow-enderpearl flag is on, you can spam pear inside areasl, the default 1 second cooldown is just gone. And also installing a pearl cooldown plugin doesn't work inside a worldguard area.

**To Reproduce**
1. Allow pearls in an area
2. Go to that area
3. Keep right button down while holding many pearls
4. Watch as like they are all thrown at a very fast interval
5. Go outside the area
6. Try the same thing
7. See the default pocketmine pearl cooldown.

**Expected behavior**
There should be a cooldown on enderpearls that is 20 tics (or 1 second)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIN10
 - Browser: Opera
 - Version: 1.1.7 from poggit

**Additional context**

**Comment by awgybop1** [comment] 2020-10-18 19:05
I'm not sure how the enderpearl system is made but it definitely should not be doing that.
It shouldn't be doing anything different if the flag is not set to deny, I'll check into it.

**Comment by awgybop1** [comment] 2020-10-18 19:18
Confirmed issue, will be fixing ASAP.

**Comment by ItsMax123** [comment] 2020-10-25 18:51
I just found out that even if I download an EnderPearlCooldown plugin it doesnt work. The EnderPearlCooldown plugin just doesnt work inside worldguard regions.

**Comment by ItsMax123** [comment] 2020-10-29 01:16
Found a fix! Basically, I tested the pluginbypass and it fixed the pearl glitch BUT also when I do that then it makes it so the block/place is doesnt work anymore. So I just made my own seperate plugin and just coded so people cant break and place within the coords i wanted. Complicated fix which could probably be done easier but atleast it works! Hopefully this helps you spot the error and fix it! You can close the issue when you read this. TY

**Comment by suerion** [comment] 2020-10-29 04:01
I think, i will look on this tomorrow again, i think, this has nothing to do with pluginbypass, i will look on it again

**Comment by awgybop1** [comment] 2020-11-20 17:08
This is a very weird issue caused by WorldGuard that globally removes the Enderpearl Cooldown - which doesn't make any sense. I'll have to do a lot of experimenting to figure out why this is happening, but I will let you know once I find a fix for it!

**Comment by suerion** [comment] 2021-09-24 03:47
I had merged the pull request from @ItsMax123  #221 i had tested it, and it worked fine.... I hope i get an better pc soon, 

bluescreens overwhelming my system...

**Closed by suerion** 2021-09-24 03:47 UTC
Labels: bug, To-do
